version: "3"
services:
  app:
    build: .
    
    #image: maxime1907/filegator
    volumes: 
      - ./data:/data:rw
      - ./scripts/:/config/:rw
      #- ./data/users.json.blank:/config/www/private/users.json.blank
    ports:
      - "8081:888"
    environment:
       FM_USERNAME: user
       FM_PASSWORD: password
       FM_PORT: "888"